#!/bin/bash

echo "========================================"
echo "  Jenkins CI/CD Pipeline - Build Output"
echo "========================================"
echo ""
echo "Build triggered at : $(date)"
echo "Running on host    : $(hostname)"
echo "Current user       : $(whoami)"
echo "Working directory  : $(pwd)"
echo ""
echo "--- Git Info ---"
echo "Branch  : ${GIT_BRANCH:-N/A}"
echo "Commit  : ${GIT_COMMIT:-N/A}"
echo "Repo URL: ${GIT_URL:-N/A}"
echo ""
echo "--- System Info ---"
echo "OS      : $(uname -a)"
echo "Uptime  : $(uptime)"
echo ""
echo "Build completed successfully!"
